<a href="https://colab.research.google.com/github/Aditi15091999/PDV-Assignments/blob/main/Numpy_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Create a 4X2 integer array and Prints its attributes

In [65]:
import numpy as np
arr=np.random.randint(100,size=(4,2))
arr

array([[28,  6],
       [ 0,  2],
       [72, 71],
       [97, 34]])

2.Create 5*2 array from range between 100 and 200 with step 10

In [66]:
arr1=np.arange(100,200,10).reshape(5,2)
arr1

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

 3.odd rows and even columns from numpy ARRAYS

In [67]:
arr2=np.arange(20).reshape(4,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [68]:
arr2[::2, 1::2]

array([[ 1,  3],
       [11, 13]])

4.Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element

In [69]:
arr3=np.random.randint(50,80,10).reshape(2,5)
print(arr3)

arr4=np.random.randint(1,30,10).reshape(2,5)
print(arr4)

result=arr3+arr4
print("The resulting array is\n",result)

result=np.square(result)
print("the squared array is\n",result)

[[52 61 75 76 74]
 [73 79 67 63 67]]
[[ 8 16 28 15 27]
 [ 3  8 14 12 10]]
The resulting array is
 [[ 60  77 103  91 101]
 [ 76  87  81  75  77]]
the squared array is
 [[ 3600  5929 10609  8281 10201]
 [ 5776  7569  6561  5625  5929]]


5. Split the array into four equal-sized sub-arrays

In [70]:
arr5=np.arange(50)
np.split(arr5,10)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24]),
 array([25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34]),
 array([35, 36, 37, 38, 39]),
 array([40, 41, 42, 43, 44]),
 array([45, 46, 47, 48, 49])]

6. Print max from axis 0 and minfrom axis 1 from the 2-D arrayof your choice.

In [71]:
arr6=np.array([[1,2,3,4],[21,34,56,67],[20,6,7,8],[9,46,11,12]])
print(arr6)
print("The max from axis 0 is")
max=np.amax(arr6,0)
print(max)
print("The min from axis 1 is")
print(np.amin(arr6,1))

[[ 1  2  3  4]
 [21 34 56 67]
 [20  6  7  8]
 [ 9 46 11 12]]
The max from axis 0 is
[21 46 56 67]
The min from axis 1 is
[ 1 21  6  9]


7.Delete the second column from a givenarray and insert the new column in its place.

In [72]:
arr_del=np.delete(arr6,1,1)
arr_del

array([[ 1,  3,  4],
       [21, 56, 67],
       [20,  7,  8],
       [ 9, 11, 12]])

In [73]:
new_col=[[12,14,16,45]]
arr_del=np.insert(arr_del,1,new_col,1)
arr_del

array([[ 1, 12,  3,  4],
       [21, 14, 56, 67],
       [20, 16,  7,  8],
       [ 9, 45, 11, 12]])